const rows = [
 {
   "Customer": "Lemonaid Health",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "At-home",
   "C19 Priority": "High",
   "C19 Stage": "Production, Initial",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "At home COVID-19  rapid test.",
   "C19 URL": "https://www.lemonaidhealth.com/blog/covid-19-coronavirus-testing-service",
   "Description": "Icebreaker Health, dba Lemonaid Health, is building a next generation telemedicine platform that combines the best of store-and-forward and synchronous technologies. The company's platform delivers standardized care at radically low cost. Its secure platform augments the expertise and experience of doctors to deliver evidence-based care through Android and iOS mobile apps.",
   "C19 Soln": "At home teating w/Scanwell $70.  Blood test?\n",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "paul@lemonaid.com, simon@lemonaid.com",
   "Other emails": "paul@lemonaid.com, simon@lemonaid.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "11/19/2018 4:42pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "LetsGetChecked",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "At-home",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "Canada,US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "At home COVID-19  rapid test.",
   "C19 URL": "https://www.letsgetchecked.com/us/en/",
   "Description": "LetsGetChecked (LGC) is a home testing platform, enabling people to access lab tests from within the home, along side clinical (physician and nurse) support via telemedicine. LGC owns all elements of the process, from manufacturing of the test-kits, dispatch, lab analysis, and clinical network. ",
   "C19 Soln": "We have developed a rapid response to COVID-19, with a two-pronged testing approach from within the home:  1. POC - the kit will contain a point of care test that will allow a patient to be diagnosed in the home within 15 minutes. This is a screen but will allow for immediate self-quarantine. 2. PCR based test - the patient will also collect a sample (nasal and throat) using swabs from within the test-kit and send it back using a prepaid envelope provided within the test-kit. This will be classified as a confirmatory test and/or diagnosis.\n\nFirst market is Health Care workers and First Line Responders in the USA",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Eoin Hyland, peter foley",
   "C19 Primary Email": "eoin@letsgetchecked.com, peter@letsgetchecked.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "LetsGetChecked",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Scanwell",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "At-home",
   "C19 Priority": "Medium",
   "C19 Stage": "Production, Initial",
   "Delivery Regions": "",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "At home COVID-19  rapid test.",
   "C19 URL": "",
   "Description": "Developer of an urine testing kit designed to help users to test their urine at home. The company's testing kit helps in at-home urinary tract infection test and treatment service by taking the same urine test performed in doctor's offices, clinics, and hospitals and making it available to anyone who has a Scanwell UTI test kit and smartphone, enabling people to avoid the time and expense of in-person doctor visits without sacrificing the quality of care",
   "C19 Soln": "+LemonAid for at home COVID Test\n",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "stephen@scanwellhealth.com, jack@scanwellhealth.com",
   "Other emails": "stephen@scanwellhealth.com, jack@scanwellhealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "11/20/2019 3:32pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Genalyte",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "LDT",
   "C19 Priority": "High",
   "C19 Stage": "Initial",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "Multiplexed, Rapid COVID-19 Serology Testing ",
   "C19 URL": "",
   "Description": "Genalyte is transforming the doctor-patient relationship by providing rapid diagnostic testing right in the doctor's office. The company's technology delivers results to physicians in minutes from just a single drop of blood, yielding better outcomes for the patient, empowering doctors to be more effective, and creating a more efficient healthcare system.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Cary Gunn",
   "C19 Primary Email": "cary@genalyte.com",
   "Other emails": "cary@genalyte.com, muzammil@genalyte.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "9/24/2018 5:11am",
   "COVID Survey": "Genalyte",
   "C19DxLink": "Genalyte",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "diagnostics.ai ltd",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "LDT",
   "C19 Priority": "Medium",
   "C19 Stage": "Initial",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "Automate QA for COVID19 and higher test throughput",
   "C19 URL": "",
   "Description": "Using AI to automate testing for infectious diseases (including Covid-19 and others, commercially). Working with hospitals and clinical labs to deliver more accurate, more standardised and more efficient testing for patients, doctors and hospitals.",
   "C19 Soln": "Automate QA for COVID19 and higher test throughput\n",
   "C19 Notes": "",
   "C19 Installs": "Kings (NHS Trust)",
   "C19 Pro Bono": "checked",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Aron Cohen",
   "C19 Primary Email": "aron@diagnostics.ai",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "diagnostics.ai ltd",
   "C19DxLink": "",
   "C19OpsLink": "Diagnostics.ai",
   "C19TxLink": ""
 },
 {
   "Customer": "IDbyDNA",
   "C19 Cat": "Diagnostic",
   "C19 SubCat": "LDT",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "NGS detection of COVID-19",
   "C19 URL": "",
   "Description": "NGS for infectious disease\n",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "jfield@idbydna.com, qli@idbydna.com, gcliao@idbydna.com, sflygare@idbydna.com, kbroadbent@idbydna.com",
   "Other emails": "jfield@idbydna.com, qli@idbydna.com, gcliao@idbydna.com, sflygare@idbydna.com, kbroadbent@idbydna.com",
   "Type": "Startup",
   "Geo": "",
   "Created": "1/21/2019 8:30pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Xealth",
   "C19 Cat": "Ops",
   "C19 SubCat": "Consumer",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of a digital prescribing platform designed to connect patients and doctors easily. The company's platform can prescribe and monitor digital health care content, apps, devices and services from within their electronic health record (EHR) charting interface, enabling healthcare teams to order digital content and services as easily as they do orders and medications today.",
   "C19 Soln": "1) Sending patient education tools (videos, articles, screenings, 'how to telehealth', etc) materials to patients in automated PRE-VISIT prepartion.  2) Sending Remote Patient Monitoring tools (Apps, Screenings, Pathways) to Suspected/Confirmed Covid+ patients post diagnosis from visit.  3) Sending Covid Response (Quarantine in a Box) packages to patients home for quarantined individuals/families.  This could include RPM devices (pulse oximiters/thermomenters), Food/Meals, Essentials for safety and remote monitoring.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Mike McSherry",
   "C19 Primary Email": "mike.mcsherry@xealth.com",
   "Other emails": "mike.mcsherry@xealth.io, aaron.sheedy@xealth.io, eric.fu@xealth.io, cynthia.church@xealth.com, evelyn.daniels@xealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "8/7/2018 3:48am",
   "COVID Survey": "Xealth",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "HealthGorilla",
   "C19 Cat": "Ops",
   "C19 SubCat": "APIs",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Health Gorilla is a provider in digital health. Health Gorilla's nationwide clinical network connects doctors, vendors, and patients within a single, secure interface ?Ž creating a closed loop of communication and transforming how care is managed. Health Gorilla automates lab results, referrals and test results for physicians and medical facilities, which provides better communication between all parties involved, and leads to better communication and an overall healthier population. Health Gorilla is HIPAA compliant and MU2-certified, available online or on-the-go",
   "C19 Soln": "2 weeks ago, we became one of the first applications to launch COVID-19 test ordering and resulting with national labs including LabCorp, Quest, and BioReference. Today, we're publishing preliminary findings on COVID-19 test results that have been processed through Health Gorilla. Among these findings include the percentage of cases that tested positive, average turnaround time per test, and growth in COVID-19 testing volume among our user base. ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "syaskin@healthgorilla.com, azudin@healthgorilla.com, azaman@healthgorilla.com",
   "Other emails": "syaskin@healthgorilla.com, azudin@healthgorilla.com, azaman@healthgorilla.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Human API",
   "C19 Cat": "Ops",
   "C19 SubCat": "APIs",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "Yes",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Human API lets application developers create meaning from data streams of personal health through one simple, secure API. The company exposes each data stream as an endpoint that can be called, and the data source is abstracted away, leaving one simple, clean, stable API.",
   "C19 Soln": "Our solution is a ƒ??No-Touchƒ? EHR authorization and retrieval platform.  This platform provides an on-line, consumer-driven, experience for the collection of medical history that removes in-person visits or burdensome requests on physician office.  More here: https://www.humanapi.co/covid-19-response\n\n\nWe enable healthcare providers (Telemedicine, Urgent Care, etc) access to a consumer's full patient medical history 100% electronically - without the need to burden previous medical practitioners to pull records.",
   "C19 Notes": "We have 70+ enterprise clients leveraging our platform of which the COVD solution is a small part of, including some of the largest life insurance companies in the U.S., such as AAA and Guardian.  ",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "checked",
   "C19 Primary Contact": "Christian Wieland",
   "C19 Primary Email": "christian@humanapi.co",
   "Other emails": "andrei@humanapi.co, scott@humanapi.co (email bounce back), brian.kelly@humanapi.co, christian@humanapi.co, john@humanapi.co",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/27/2018 10:53pm",
   "COVID Survey": "HumanAPI",
   "C19DxLink": "",
   "C19OpsLink": "HumanAPI",
   "C19TxLink": ""
 },
 {
   "Customer": "Redox",
   "C19 Cat": "Ops",
   "C19 SubCat": "APIs",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "100Health, dba Redox, is the modern API for healthcare. the company allows best in class software to easily and securely interoperate with EHRs by connecting to existing health system infrastructure. Software applications connect to Redox once and integrate with any health system they sell to through our standardized data models.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "luke@redoxengine.com, james@redoxengine.com, niko@redoxengine.com, devin@redoxengine.com, brendan@redoxengine.com, matt@redoxengine.com, samantha@redoxengine.com, john@redoxengine.com",
   "Other emails": "luke@redoxengine.com, james@redoxengine.com, niko@redoxengine.com, devin@redoxengine.com, brendan@redoxengine.com, matt@redoxengine.com, samantha@redoxengine.com, john@redoxengine.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Particle Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "APIs",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of a platform designed to allows patients and consumers to share their medical information. The company is leveraging blockchain technology to enable a single health record-tying together previously disparate information from a patient's various doctors and yielding valuable data insights in the process, enabling clients to better serve your patients, policyholders or customers.",
   "C19 Soln": "We are working with several telemedicine companies to provide free access to electronic medical records on any patient instantly via our API.  We are integrated with 90% of EMRs and can pull records for treatment without consent/credentials.\n\nSeveral telemedicine companies are using our solution right now for COVID-19 screening.  The only one I can reference right now is SimplyVital Health.  Here's a recent article about them using Particle's API for COVID screening. \n\nWe are certified by CommonWell Alliance and Carequality (ONC/Sequoia Project) to be conducting queries in a HIPAA compliant & secure method.  \n",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "checked",
   "C19 Primary Contact": "Troy Bannister",
   "C19 Primary Email": "Troy.Bannister@ParticleHealth.com",
   "Other emails": "troy.bannister@particlehealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "1/6/2020 4:29pm",
   "COVID Survey": "Particle Health",
   "C19DxLink": "",
   "C19OpsLink": "Particle Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Drchrono",
   "C19 Cat": "Ops",
   "C19 SubCat": "EHR",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US,Canada",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Drchrono provides a cloud and web based Electronic Health Record access with a focus on the iPad and iPhone. The platform offers scheduling, patient reminders and billing systems, ePrescribing, and patient check-in pads. The company's services enables healthcare providers to have a choice of the applications, technology and back office resources needed without the complexity of hospital level systems.",
   "C19 Soln": "Expanding Telemedicine to entire U.S. population to keep providers in business and help flatten the curve of Coronavirus by keeping patients at home for Corornavirus related care and routine medical and mental health care.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Michael Nusimow",
   "C19 Primary Email": "ceo@drchrono.com",
   "Other emails": "daniel@drchrono.com, michael@drchrono.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "10/2/2018 4:49pm",
   "COVID Survey": "DrChrono",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Buoy Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Buoy Health, formerly QUR, is a computerized, concierge doctor, providing personalized medical information in place of late-night Google searches and scary internet forums. At its core, Buoy is a machine-learning, adaptive diagnosis generator with the ability to express compassion and humor. A patient inputs their symptoms and is then asked a series of adaptive questions that are narrowing down the possible diagnoses behind-the-scenes. At the conclusion of a \"visit\", the patient is presented with possible diagnoses, given the option to be followed-up, and if necessary, suggestions on where to find the appropriate level of care.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "eddie@buoyhealth.com, andrew@buoyhealth.com",
   "Other emails": "eddie@buoyhealth.com, andrew@buoyhealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Notable Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of a voice-powered healthcare platform designed to enrich every physician-patient interaction. The company's platform includes a voice-powered app built for the Apple watch that automatically structures physician-patient conversations, dictations, orders and recommends the appropriate billing codes in a secure manner using AI driven robotic process automation, enabling physicians to save time while updating electronic health records.",
   "C19 Soln": "We have designed a COVID-19 virtual assessment, digital triage, and remote monitoring solution for health systems. We 1) use robotic process automation to ingest the scheduled appointments for a clinic/health system, 2) send a text message link to all patients 48 hours before their scheduled appointment, 3) conduct a mobile virtual assessment of their probability of COVID-19 and risk of complications, 4) triage patients to the appropriate care destination (virtual care, emergency room, drive-thru testing, etc.), 5) share the responses with health systems in a population health dashboard, and 6) conduct daily remote patient monitoring of any at-risk individuals.   ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Muthu Alagappan",
   "C19 Primary Email": "muthu@notablehealth.com",
   "Other emails": "pranay@notablehealth.com, justin@notablehealth.com, justin@vivaahealth.com, regina@notablehealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/5/2018 12:51pm",
   "COVID Survey": "Notable Health",
   "C19DxLink": "",
   "C19OpsLink": "Notable Health",
   "C19TxLink": ""
 },
 {
   "Customer": "ALTIBBI",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "MENA",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Altibbi is an end to end digital health platform. We provide On demand 24/7 primary care Telehealth in MENA. We also specialize in medical content (2M pages) and launched a cloud based Clinic Management system with video capabilities for remote visits with physicians.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Jalil Allabadi",
   "C19 Primary Email": "jalil@altibbi.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "ALTIBBI",
   "C19DxLink": "",
   "C19OpsLink": "Altibbi",
   "C19TxLink": ""
 },
 {
   "Customer": "Mediktor",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "The most accurate AI based Medical Assistant for triage, pre-diagnosis and decision making support",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Roger Forcada",
   "C19 Primary Email": "rforcada@mediktor.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Mediktor",
   "C19DxLink": "",
   "C19OpsLink": "Mediktor",
   "C19TxLink": ""
 },
 {
   "Customer": "Memora Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of healthcare technology designed to automate patient follow-up and improves nursing operations in hospitals. The company's platform consists of a patient-facing, AI-backed conversational interface and a physician-facing web application and includes automated patient reminders, care instructions, and responses to common questions via SMS, enabling healthcare teams to digitize and scale their patient communication efforts. The software additionally provide hospitals with comprehensive analytics on allocation of staff time and quality of care.",
   "C19 Soln": "Memora has launched a system for health systems to implement their triage pathways for patients over SMS. People can text in to a phone number and go through preliminary triage to determine if they need a telemedicine visit or are at-risk; this additionally includes the screening of physicians for COVID exposure and burnout. This is helping to divert low-risk volume away from ERs so that health systems can manage the outbreak and also assure their staff is cared for during this crisis.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Manav Sevak",
   "C19 Primary Email": "manav@memorahealth.com",
   "Other emails": "manav@memorahealth.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/23/2018 5:11am",
   "COVID Survey": "Memora Health",
   "C19DxLink": "",
   "C19OpsLink": "Memora Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Vital Software (dba Vital)",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (External)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Operator of a hospital emergency software platform intended to make it easier to coordinate care and prioritize patients. The company provides uses artificial intelligence and natural language processing in the emergency room to triage patients before they see a doctor, helping doctors and nurses to coordinate care and prioritize patients with a fast, reliable, incredibly useable system.",
   "C19 Soln": "\"C19Check.com is a public-facing website designed to guide an individual through self-triage and next steps while mitigating surge\n burden on the healthcare system through public education and outbreak analytics.\"",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "apatzer@vitaler.com",
   "Other emails": "apatzer@vitaler.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/27/2019 8:10pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "Vitaler",
   "C19TxLink": ""
 },
 {
   "Customer": "Biobeat Technologies Ltd.",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "High",
   "C19 Stage": "Initial",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "The Biobeat monitoring platform allows continuous monitoring using a wireless, medical grade, non-invasive optical sensor, measuring 16 different vital signs including cuffless blood pressure, heart rate, blood oxygen saturation, respiratory rate, stroke volume, cardiac output, systemic vascular resistance and temperature ƒ?? all in one small wearable device. The data is automatically transmitted in real time to the cloud and can be accessed from anywhere by the medical staff, providing relevant alerts when a change is detected. This dramatically reduces the direct contact between patients and health care providers, decreasing the risk for secondary exposure of the medical teams.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Lior Ben Shettrit",
   "C19 Primary Email": "lior@bio-beat.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Biobeat Technologies Ltd.",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Current Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US,EU",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "uses a single medical wearable device to continuously monitor patients from the upper arm across more health indicators than any other single device on the market. Crucially, the company then uses this data to identify, in real-time, patients at risk of deteriorating. By alerting doctors and nurses early, they can take action, potentially saving the patient's life, improving outcomes, and allowing them to return home sooner.",
   "C19 Soln": "Current Health is a patient monitoring platform that combines a continuous vital-sign sensor, connectivity with other devices, alarms, and telemedicine video call capability into a single platform. Our wearable can be placed on patients at risk for COVID-19 -- in the hospital, ED, even parking lot -- or shipped directly to the patient's home. We're helping hospitals preserve capacity by discharging more patients early & stoping hospitalizations in the first place, as well as increasing the number of patients that can be monitored and kept safe. Based on current orders, we expect to deploy to approx 10,000 patients in the next 2 weeks alone.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Christopher McCann",
   "C19 Primary Email": "christopher@currenthealth.com",
   "Other emails": "christopher.mccann@currenthealth.com",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "4/29/2019 5:46pm",
   "COVID Survey": "Current Health",
   "C19DxLink": "",
   "C19OpsLink": "Current Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Validic",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Initial",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Motivation Science is the developer of Validic, a digital health platform that provides a simple connection to secure, standardized data from specialized digital health technologies, such as wellness applications, wearables, fitness equipment and clinical devices.",
   "C19 Soln": "Validic is offering a standalone remote patient monitoring (RPM) solution specifically designed to continuously monitor vulnerable or exposed populations for the emergence of COVID-19 symptoms. The first phase of Validicƒ??s standalone RPM solution enables patients to enter their symptoms, body temperature, and SPO2 readings from their home devices into a secure, web-hosted portal. The patientƒ??s home health data are made accessible to clinicians and treatment professionals via a triage dashboard.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Ash Needham",
   "C19 Primary Email": "ashley@validic.com",
   "Other emails": "drew@validic.com, john.george@validic.com, ashley@validic.com, meaghan.early@validic.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "Validic",
   "C19DxLink": "",
   "C19OpsLink": "Validic",
   "C19TxLink": ""
 },
 {
   "Customer": "Oxehealth",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "UK,Ireland,Sweden,Germany",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Non-contact monitoring of vital signs (pulse rate, breathing rate) and movement for patients in hospitals. Currently deployed in mental health hospitals, acute hospitals, police cells, prison cells and elderly care homes. Using an optical sensor and infrared illumination. Certified medical device",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Charlotte Wood",
   "C19 Primary Email": "charlotte.wood@oxehealth.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Oxehealth",
   "C19DxLink": "",
   "C19OpsLink": "Oxe Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Spire Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Spire Health is the leader in remote patient monitoring for respiratory diseases. Our commercial stage, clinically-proven platform is already widely deployed in pulmonary/critical care practices. It can be used to remotely monitor the disease progression of COVID-19 patients or at-risk individuals.",
   "C19 Soln": "The Spire Health solution includes Health Tags, small wearable devices that are attached to a user's existing clothing and that can continuously monitor respiratory rate/breathing patterns (the WHO has indicated respiratory rate is a key indicator of worsening severity of the Covid-19 virus).  By providing Health Tags to exposed or infected individuals, Spire can continuously monitor individuals at home, identifying the ~20% of patients that need additional care and helping keep the other ~80% at home, alleviating hospital capacity issues and reducing the potential for additional transmission.  The system can automatically identify patients that have reached a set threshold (e.g., 30 breaths per minute) or have deviated substantially from their own baseline (e.g., heart rate 20% higher than average for 6 or more consecutive hours), enabling follow up from Spire's clinical team and/or other healthcare providers.  ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Brad Rodrigues",
   "C19 Primary Email": "brad@spirehealth.com",
   "Other emails": "jpalley@gmail.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "12/4/2019 9:31pm",
   "COVID Survey": "Spire Health",
   "C19DxLink": "",
   "C19OpsLink": "Spire Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Sentinel Healthcare",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Operator of a remote healthcare management platform intended to tackle hypertension epidemic and chronic diseases. The company's platform remotely monitor and deliver clinical recommendations to patients with high blood pressure, enabling patients to achieve blood pressure control more quickly than standard of care.",
   "C19 Soln": " COVID-19 quarantine management program for remotely monitoring quarantined patients and healthcare workers who have been exposed.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Noah Manders",
   "C19 Primary Email": "noah@sentinel.healthcare",
   "Other emails": "nirav@sentinel.healthcare",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "12/1/2019 12:40am",
   "COVID Survey": "Sentinel Healthcare",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "EarlySense",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "EarlySense provides contact-free, continuous monitoring solutions for the medical and consumer digital health markets. EarlySense's patented sensor and advanced algorithms monitor and analyze cardiac, respiratory, sleep and motion parameters. Used in hospitals and healthcare facilities worldwide, EarlySense assists clinicians in early detection of patient deterioration, helping to prevent adverse events, including code blues, preventable ICU transfers, patient falls and pressure ulcers. Additionally, the company's myEarlySense smart home-compatible consumer solution brings hospital-proven technology to the home, providing valuable data regarding wellness and sleep.",
   "C19 Soln": "EarlySense developed a system that continuously monitors a patientƒ??s heart rate,  respiratory rate, and motion which gives the medical team the ability to monitor Covid-19 patients from a distance and prevent deterioration in case of respiratory-related cases.   In addition to that, we are working on the next generation of the system. This solution should help the medical teams to monitor patients at home.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Ziv Leinwand",
   "C19 Primary Email": "ziv.leinwand@earlysense.com",
   "Other emails": "AvnerH@earlysense.com, Shirel.Titer@earlysense.com, Liat.Tsoref@earlysense.com, Matt.Johnson@earlysense.com",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "10/2/2018 4:52pm",
   "COVID Survey": "EarlySense",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "BioFourmis",
   "C19 Cat": "Ops",
   "C19 SubCat": "Monitoring",
   "C19 Priority": "Medium",
   "C19 Stage": "Pilot/Beta",
   "Delivery Regions": "",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Provider of a health analytics platform intended to analyse physiology data from clinical grade wearables. The company's health analytics platform uses Artificial Intelligence (AI) to integrate and analyze continuous physiology data from clinical grade wearables and to detect personalized patterns that can predict a patient's health deterioration, enabling medical professionals to intervene days before a critical event.",
   "C19 Soln": "Biovitals? platform to remotely monitor and manage suspects and patients with COVID-19. The platform is built and hosted on AWS cloud and primarily focuses on continuously monitoring patients using wearable biosensor, Everion? combined with our FDA cleared Biovitals Analytics Engine to detect physiology changes precursors to symptoms and monitor deterioration and progression of disease.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "",
   "Other emails": "kuldeep@biofourmis.com",
   "Type": "Startup",
   "Geo": "APJ",
   "Created": "10/25/2019 3:21pm",
   "COVID Survey": "Biofourmis",
   "C19DxLink": "",
   "C19OpsLink": "Biofourmis",
   "C19TxLink": ""
 },
 {
   "Customer": "Qventus",
   "C19 Cat": "Ops",
   "C19 SubCat": "Analytics",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "analyticsMD uses a hospital's data along with proprietary external data signals to help managers proactively manage day-to-day operations. analyticsMD's algorithms analyze hospital data along important operational and clinical metrics, allowing hospital staff to both monitor operational performance and automatically diagnose operational issues in real time. In addition, analyticsMD's machine-learning based forecasting techniques enable hospitals to predict patient volumes and optimally allocate resources ? such as staff, beds, and rooms ? to meet this demand. These insights are delivered to staff in the workflows with which they are already accustomed.",
   "C19 Soln": "Optimizing hospital operations. We are powering several health system command centers with actionable information around capacity (negative airflow rooms, ventilators etc.) and information on dischargeable patients.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "checked",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "mudit@qventus.com",
   "Other emails": "davidatashroo@gmail.com, mudit@qventus.com, natalie@qventus.com (email bounce back), brent@qventus.com, greg@qventus.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "Qventus",
   "C19DxLink": "",
   "C19OpsLink": "Qventus",
   "C19TxLink": ""
 },
 {
   "Customer": "MDmetrix",
   "C19 Cat": "Ops",
   "C19 SubCat": "Analytics",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Based in Seattle, MDmetrix is a proven, AWS-hosted clinical data intelligence platform that empowers clinicians to transform patient care by leveraging real-world data from their hospitalƒ??s EMR. Uniquely, MDmetrix puts into the hands of every clinical leader a ƒ??Mission Control Centerƒ? that allows them to easily visualize clinical performance across patients, so that they can quickly adapt and improve care across teams, conditions, and protocols. If we move quickly, MDmetrix and Amazon can partner to make a COVID-19 Mission Control available to hospitals in dire need.",
   "C19 Soln": "Together, we can assist UW Harborview and UW Medical Center in deploying a centralized data sharing platform that would provide hospital administrators, frontline clinicians, public health leaders, and researchers with vital visibility at a critical time. With access to COVID-19 Mission Control, key stakeholders could look across their own hospitals and across the larger community to monitor respiratory-related ED visits, evaluate treatment care pathways, and assess burdens on limited resources. With this data-driven management of COVID-19, clinicians would not only optimize care within their hospitals but would also accelerate and coordinate care improvement across the healthcare system.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Warren Ratliff",
   "C19 Primary Email": "warren@mdmetrix.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "MDmetrix",
   "C19DxLink": "",
   "C19OpsLink": "MdMetrix",
   "C19TxLink": ""
 },
 {
   "Customer": "ClosedLoop",
   "C19 Cat": "Ops",
   "C19 SubCat": "Risk",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "ClosedLoop.ai is an artificial intelligence-based precision health platform that allows users to do three things: integrate data from a variety of disparate sources (Claims, EHR, Genomic, Wearable, Environmental, Social), create AI models to predict health outcomes and support clinical decisions optimized for individual patients, and monitor and aggregate the impact of interventions over time to make the best decision for the next patient.",
   "C19 Soln": "The COVID-19 Vulnerability Index - Open Source Data Science to Fight COVID-19.  The CV19 Index is an open source, AI-based predictive model that identifies people who are likely to have a heightened vulnerability to severe complications from COVID-19 (commonly referred to as ƒ??The Coronavirusƒ?).  The CV19 Index is intended to help hospitals, federal / state / local public health agencies and other healthcare organizations in their work to identify, plan for, respond to, and reduce the impact of COVID-19 in their communities. ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Andrew Eye",
   "C19 Primary Email": "andrew.eye@closedloop.ai",
   "Other emails": "andrew.eye@closedloop.ai, dave.decaprio@closedloop.ai, carol.mccall@closedloop.ai, doug.keyes@closedloop.ai",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/5/2018 12:51pm",
   "COVID Survey": "ClosedLoop",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Strata Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (Internal)",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "UK,Canada",
   "FDA EUA": "",
   "C19 ProBono Offering": "Yes",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "",
   "C19 Soln": "A solution providing critical care triage with ventilator waitlisting and prioritization, supporting frontline clinicians when allocating scarce resources during the pandemic.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Jen Hoecht",
   "C19 Primary Email": "jen@stratahealth.com",
   "Other emails": "",
   "Type": "",
   "Geo": "AMER",
   "Created": "2/17/2020 1:16pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "Strata Health Solutions",
   "C19TxLink": ""
 },
 {
   "Customer": "Asparia",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (Internal)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Automatingadministrative workflows in healthcare delivery organizations that require communications between staff and patients. Asparia chatbot automates and personalizes these communications at scale by directly triggering the workflows from the EHR, engaging patients via conversational texting and completing the transaction in the EHR without any staff intervention.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Kamal Anand",
   "C19 Primary Email": "kamal@asparia.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Asparia",
   "C19DxLink": "",
   "C19OpsLink": "Asparia",
   "C19TxLink": ""
 },
 {
   "Customer": "Biosurfit",
   "C19 Cat": "Ops",
   "C19 SubCat": "Triage (Internal)",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Portugal",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Creates medical devices that can perform blood scans). Working with the Red Cross Hospital and Mercedes-Benz.io",
   "C19 Soln": "Triage of patients with Covid-19. The patients sign up into the app, and answer a short query regarding their health condition. After the sign up the patients go to a drive-through (a triage center) where their app gets scanned (each patient has a unique QR code assigned to them) by the medical team onsite.\nThe medical team has their own companion app that they use to insert patient-relevant information and place the result of onsite tests that are performed to each patient.\nThe medical team will take 2 drops of blood of each patient and run a series of tests that will take between 8 minutes to 3 hours. With those results they will inform the patient about the best procedure for them. The medical app scans QR codes from the test machines to avoid the medical team to insert a huge amount of data, speeding up the process.  Identified suspected patients with Covid-19 assess their health status and direct patients to primary health care facilities according to the defined procedure.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "",
   "Other emails": "",
   "Type": "",
   "Geo": "",
   "Created": "3/25/2020 12:05pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Consejo Sano",
   "C19 Cat": "Ops",
   "C19 SubCat": "Pt Comms",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "ConsejoSano helps navigate underserved, multicultural, Medicare, Medicaid, and Commercial consumers through the complex healthcare ecosystem in the US. We primarily do this via culturally-adapted SMS-led content including educational campaigns, culturally-adapted screening tools, and more. Our Cultural Determinants Engineƒ?› allows us to uncover opportunities to connect with unique and diverse populations based on factors that impact their everyday lives, and to communicate critical health information with them in a way that resonates, quickly, and at scale. ",
   "C19 Soln": "ConsejoSano navigates multicultural, underserved, and diverse Medicaid, Medicare, and Commercially insured populations to timely and accurate COVID-19 education primarily using bidirectional (2-way) SMS, with escalations to live outbound calls (in 17+ languages) and email, if necessary. Once education is provided, we are able to conduct a culturally adapted screener (below high school reading level in English, plus a variety of other languages), and work with the member/patientƒ??s health plan and/or provider to provide disease-state education, connect them to telemedicine solutions, in-person care when necessary, and testing facilities. Information is also provided as it relates to Cultural Determinants of Health, so we can direct individuals to appropriate Community Based Organizations (CBOs) and other safety net organizations. ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Gary Rosenfield",
   "C19 Primary Email": "gary.rosenfield@consejosano.com",
   "Other emails": "abner.mason@consejosano.com, ahmad.jubran@consejosano.com, tony.campos@consejosano.com, vik.bakhru@consejosano.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/3/2020 8:38pm",
   "COVID Survey": "\"ConsejoSano, Inc. \"",
   "C19DxLink": "",
   "C19OpsLink": "Consejo sano",
   "C19TxLink": ""
 },
 {
   "Customer": "Myosotis GmbH",
   "C19 Cat": "Ops",
   "C19 SubCat": "Pt Comms",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Germany,UK",
   "FDA EUA": "",
   "C19 ProBono Offering": "Yes",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "",
   "C19 Soln": "Allowing care home staff to communicate safely and efficiently with the families of people in the need of care in order to enable what the virus prevents - togetherness.  ",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "",
   "Other emails": "",
   "Type": "",
   "Geo": "",
   "Created": "3/26/2020 1:12am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "Myosotis GmbH",
   "C19TxLink": ""
 },
 {
   "Customer": "Luma Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Pt Comms",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Provides end to end patient communication and access and has built a suite of COVID-19 specific solutions already deployed to market.",
   "C19 Soln": "COVID-19 patient messaging and education through part of an Actionable Reminders product as well as bulk messaging from Broadcast products.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Aditya Bansod",
   "C19 Primary Email": "aditya@lumahealth.io",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Luma Health",
   "C19DxLink": "",
   "C19OpsLink": "Luma Health",
   "C19TxLink": ""
 },
 {
   "Customer": "HealthReveal",
   "C19 Cat": "Ops",
   "C19 SubCat": "Care Coordination",
   "C19 Priority": "High",
   "C19 Stage": "Initial",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "HealthReveal is a healthcare technology company that anticipates and mitigates adverse medical events for individuals with chronic disease. HealthReveal partners with leading providers, payers and employers to enable them to detect the onset of potentially life threatening health issues and intervene before an adverse event occurs. The company offers a cloud-based, clinical analytics solution, harnessing the power of evidence-based medicine as a foundation for machine learning.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Joshua Tauber",
   "C19 Primary Email": "josh@healthreveal.com",
   "Other emails": "lori@healthreveal.com, lonny@healthreveal.com, fnorman@healthreveal.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/24/2018 10:00pm",
   "COVID Survey": "HealthReveal",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Healthbrain GmbH",
   "C19 Cat": "Ops",
   "C19 SubCat": "Care Coordination",
   "C19 Priority": "Medium",
   "C19 Stage": "Initial",
   "Delivery Regions": "Global",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "The company provides a collaborative health care platform - Care Integrator. It involves the patient in a care team where patient outcome data is generated and aggregated with other patient data. Care teams are connected beyond departments and hospital ",
   "C19 Soln": "One of the main challenge is the threat is the overflow of the care system by to many patients with severe symptoms. With citizens/patients already remotly connected on the care integrator platform, monitoring (ePROMS, location of infection, social interactions etc.  ) allows a permanent assement of the status of the infection and will allow a much better assessment of the patient admission and triage prior of entering into the clinic. The secured channels allow a direct way of providing information to he citizen/patient.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Arnold Gloor",
   "C19 Primary Email": "arnold@healthbrain.online",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Healthbrain GmbH",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Halo Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Care Coordination",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "Yes",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Medical communication plarform\n",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "jbarreau@Halocommunications.com",
   "Other emails": "jbarreau@Halocommunications.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "1/24/2019 2:56pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "Halo Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Babylon Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "UK",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of digital healthcare applications designed to transform healthcare for everyone. The company's AI-based applications allow users to get access to reliable medical advice and make appointments with qualified GPs as well as send prescriptions electronically to a pharmacy and provides easy access to doctors' notes and recordings of video appointments online, enabling people to get access to affordable healthcare through their smartphones.",
   "C19 Soln": " The solution develops a systemic funnel of information, triage, live chat, monitoring, virtual consultation and referral for COVID-19 patient requests. The infrastructure can be shared in isolation to partners in other markets depending on the language and epidemiological model localisation requirements.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "ali.parsa@babylonhealth.com\\",
   "Other emails": "ali.parsa@babylonhealth.com, ted.schwab@babylonhealth.com, jory.tremblay@babylonhealth.com, emily.sappington@babylonhealth.com",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "7/15/2019 5:07am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "Babylon Health",
   "C19TxLink": ""
 },
 {
   "Customer": "Doctor on Demand",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Doctor On Demand is a healthcare service that provides Video Visits with board-certified physicians via smartphones, tablets, and desktop computers. Patients simply download the Doctor On Demand app on a smartphone or tablet or visit www.doctorondemand.com on their desktop computer, provide a list of their symptoms, and are instantly connected to a doctor licensed in their state for a video visit. Doctor On Demand delivers services through employers, health systems, health plans, and direct to consumers. Entrepreneurs Adam Jackson and Jay McGraw founded the company in 2013 to improve fast, easy, and cost-effective access to high quality medical care.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "adam@jacksonfound.com, hferguson@doctorondemand.com",
   "Other emails": "adam@jacksonfound.com, hferguson@doctorondemand.com, hferguson@doctorondemand.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "KRY/LIVI",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "France, Sweden",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Telemedicine -- large scale deployment Nordics\n",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "joachim@kry.se, gloria@kry.se",
   "Other emails": "joachim@kry.se, gloria@kry.se",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "6/11/2019 10:10am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "TytoCare",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "Canada, EU, Israel, Thailand, US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "TytoCare is a consumer-focused telehealth company, offering state-of-the-art, patented devices and platform that empower anyone, anywhere and anytime to perform a variety of medical examinations and seamlessly consult with a clinician.",
   "C19 Soln": "Providers are using TytoHome to monitor patients that are diagnosed with or at risk of COVID-19 and are in home isolation/quarantine.  They are using the TytoPro & Clinic to limit exposure & provide extended access for the highest risk patients at facilities including hospitals, senior care facilities, remote clinics, and quarantine locations.  TytoPro & TytoClinic are also being set up as ƒ??Covid-19 Clinicsƒ? that are physically separated/distanced from rest of the clinic or facility to contain exposure risk for other patients & providers.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Shriya Palekar",
   "C19 Primary Email": "shriyap@tytocare.com",
   "Other emails": "dedig@tytocare.com, ofert@tytocare.com, amnong@tytocare.com",
   "Type": "Startup",
   "Geo": "EMEA",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "\"Tyto Care, Inc.\"",
   "C19DxLink": "",
   "C19OpsLink": "Tytocare",
   "C19TxLink": ""
 },
 {
   "Customer": "Reliant Immune Diagnostics (MDBOX)",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Symptom-driven telemedicine visits to provide the right treatment, right away. Consumer enabled at retail outlets.",
   "C19 Soln": "we are making press announcement today...We are the FEMA designated Covid response team for Hays County and will soon likely also be for Harris, Bexar, Uvalde, Williamson and Travis Counties. We are attaching our letters from the FEMA director of Hays County, Judge Ruben Becerra, and the letter he drafted to customs for us as well. \n\nWe are about to sign finalized contracts as the covid task force for the state of Baja Mexico, a province in Canada (can?t name yet), and close to being the RPM platform for several payors across the country and possibly New York",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "",
   "Other emails": "henry.legere@reliantid.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "11/14/2019 8:30pm",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "American Well",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "American Well is a telehealth services company that brings healthcare into the homes and workplaces of patients. The Company's web and mobile telehealth platform connects patients and clinicians for live, clinically meaningful visits through video, supplemented by secure text chat and phone.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "mike.putnam@americanwell.com, mike@americanwell.com, mitch.mitchell@americanwell.com",
   "Other emails": "mike.putnam@americanwell.com, mike@americanwell.com, mitch.mitchell@americanwell.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "9/24/2018 4:59am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Zipnosis",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "Yes",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Provider of a virtual care platform designed to maximize the clinician's time and ensure clinically appropriate patient outcomes. The company's virtual care platform empowers health systems to launch proprietary branded virtual care service lines staffed with their own clinicians, guides health systems through clinical marketing, compliance and operations workflows and integrates with a health system's electronic medical record and patient portal allowing health systems to serve both existing and new patients, enabling health systems to expand access to immediate care using their own clinicians.",
   "C19 Soln": "As the leader in the asynchronous virtual care space, Zipnosis has rapidly modified it's adaptive interviews to utilize the CDC guidelines as part of the existing workflows as well as created a specific dedicated COVID-19 screener to help the worried well with their next steps. Additionally using it's existing lab workflows, the Zipnosis COVID-19 action plan involves triaging virtual care patients and qualifying them for a COVID-19 test and directing them to the right location for testing. Zipnosis is fielding international requests looking for a solution, such as Canadian insurers, Medic Mobile and Amerf in East Africa and the Nigerian CDC to name a few.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "checked",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Ethan Otterlei",
   "C19 Primary Email": "ethan@zipnosis.com",
   "Other emails": "scott.brown@zipnosis.com, andre.lheureux@zipnosis.com, jonathan.pearce@zipnosis.com, jon@zipnosis.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "\"Zipnosis, Inc.\"",
   "C19DxLink": "",
   "C19OpsLink": "Zipnosis",
   "C19TxLink": ""
 },
 {
   "Customer": "Bright.md",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "Canada,US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": " Bright.md is dedicated to making healthy happen faster with SmartExam, our modern, AI-powered, asynchronous (non-video) telehealth platform. We partner with healthcare systems looking to build loyalty and attract new patients using technology patients love, enabling them to deliver affordable, convenient, on-demand care virtually. ",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Kara Kerker",
   "C19 Primary Email": "kara@bright.md",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "Bright.md",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Firefly Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Firefly is a virtual, tech-enabled primary care alternative.  We provide longitudinal, proactive primary care to patients in the New England area and we take most commercial insurance.  Have immediate access to your care team, without leaving your home.",
   "C19 Soln": "We provide virtual primary care services, so people can get care for COVID AND all their other health concerns, without having to leave the house and go to clinics",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Jeff Greenberg",
   "C19 Primary Email": "jeff@firefly.health",
   "Other emails": "fay@firefly.health",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "2/13/2020 5:35am",
   "COVID Survey": "Firefly Health",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Thirty Madison, Inc",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Thirty Madison is a healthcare technology company improving how people manage specific conditions by expanding access to providers and medication. From diagnosis via telemedicine to treatment delivery and ongoing care management, we combine specialized care and treatment with the convenience of telemedicine. ",
   "C19 Soln": "We are repurposing our asynchronous telemedicine platform to address high volume ER use cases to help keep as many people as possible out of the ER (we'll be initially focused the the 3-5 highest volume use cases and expanding from there). There would be no onboarding or training of hospital staff required (all capacity is provided via our network) and no cost, the health system simply need to make the link available / direct patients to the portal and everything else is handled by us. This approach has been informed by our discussions with ER departments but our platform is fairly?ÿflexible so we are open to other?ÿideas for how we can help as well.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Demetri Karagas",
   "C19 Primary Email": "demetri@thirtymadison.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "\"Thirty Madison, Inc\"",
   "C19DxLink": "",
   "C19OpsLink": "Thirty Madison",
   "C19TxLink": ""
 },
 {
   "Customer": "Dispatch Health",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "We are a high-acuity, on-demand in-home care platform. We provide virtual evaluations, ER level care in the home (moderate complexity lab, IV medications, procedures and diagnostics), home hospitalization and home recovery (SNF at Home). We are available in 19 markets today and will treat over 200,000 patients in the home in 2020.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Mark Prather",
   "C19 Primary Email": "mark.prather@dispatchhealth.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "12/4/2019 4:03am",
   "COVID Survey": "DispatchHealth",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "SteadyMD",
   "C19 Cat": "Ops",
   "C19 SubCat": "Telemedicine",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Developer of a healthcare application intended to offer adequate time and attention patients deserve by doctors. The company's application pairs patients with a particular specialized doctor to address the root cause of complex issues and chronic illnesses and not just treat immediate symptoms, providing patients with comprehensive, personalized care from anywhere in the world, on any device.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Guy",
   "C19 Primary Email": "guy@steadymd.com, Jay@steadymd.com",
   "Other emails": "guy@steadymd.com, Jay@steadymd.com",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "Medinas",
   "C19 Cat": "Ops",
   "C19 SubCat": "Supply",
   "C19 Priority": "High",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "Medinas is a data-driven exchange platform that helps healthcare systems buy and sell their surplus and short-date assets.",
   "C19 Soln": "",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "",
   "C19 Primary Email": "chloe@medinas.co",
   "Other emails": "chloe@medinas.co",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "7/4/2018 3:14am",
   "COVID Survey": "medinas",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 },
 {
   "Customer": "OMNY",
   "C19 Cat": "Ops",
   "C19 SubCat": "Supply",
   "C19 Priority": "Medium",
   "C19 Stage": "Production",
   "Delivery Regions": "US",
   "FDA EUA": "",
   "C19 ProBono Offering": "",
   "C19 BD Synopsis": "",
   "C19 URL": "",
   "Description": "OMNY is a data sharing network for hospitals. We currently help share clinical and pharmaceutical data, and can facilitate sharing of critical supplychain and PPE data.",
   "C19 Soln": "PPE (masks, respirators) ventilators, and drugs/blood are going to be on extreme shortage. OMNY can help share not just available supplies but coordinate a real-time supply mesh to move product where it is needed most and balance inventory across location, all paired with COVID19 clinical data.",
   "C19 Notes": "",
   "C19 Installs": "",
   "C19 Pro Bono": "",
   "C19 Market Referenceable": "",
   "C19 Primary Contact": "Mitesh Rao",
   "C19 Primary Email": "mitesh@omnyhealth.com",
   "Other emails": "",
   "Type": "Startup",
   "Geo": "AMER",
   "Created": "3/23/2020 12:39am",
   "COVID Survey": "OMNY",
   "C19DxLink": "",
   "C19OpsLink": "",
   "C19TxLink": ""
 }
]

export default rows;